/* ============================================
   LOUBASHOP – products-data.js
   Shared product database
   ============================================ */
const PRODUCTS = [
  {
    id: 0,
    name: 'Minelab GPX 6000',
    cat: 'Série GPX – Professionnel',
    badge: 'Bestseller',
    badgeClass: '',
    img: 'XTI-Product-Photos-Large-1.png',
    stars: 5,
    reviews: 48,
    shortDesc: 'Le détecteur d\'or le plus avancé de Minelab. Technologie MLXTREME™, détection de pépites ultra-fines en profondeur.',
    longDesc: `Le Minelab GPX 6000 représente le summum de la technologie de détection d'or. Grâce à sa technologie exclusive MLXTREME™ (Multi-Period Sensing), il offre une sensibilité inégalée aux petites pépites d'or tout en maintenant une excellente profondeur de détection. Conçu pour les terrains les plus exigeants d\'Afrique de l\'Ouest, il s\'adapte automatiquement aux sols les plus minéralisés. Léger et ergonomique, il réduit la fatigue lors de longues journées de prospection.`,
    specs: [
      { label: 'Technologie', value: 'MLXTREME™ Multi-Period Sensing' },
      { label: 'Fréquences', value: 'Multi-période simultanée' },
      { label: 'Profondeur', value: 'Jusqu\'à 1,5m selon terrain' },
      { label: 'Poids', value: '2,1 kg' },
      { label: 'Autonomie', value: '10+ heures' },
      { label: 'Bobine incluse', value: 'GPX 11" Mono DD' },
      { label: 'Waterproof', value: 'Oui (tête de détection)' },
      { label: 'Garantie', value: '2 ans constructeur' },
    ],
    features: [
      'Détection automatique des sols minéralisés',
      'Mode Super-D et Monoloop interchangeable',
      'Interface tactile intuitive à 3 boutons',
      'Chargeur USB-C inclus',
      'Étui de transport rigide fourni',
    ],
    related: [1, 2, 4]
  },
  {
    id: 1,
    name: 'Minelab GPZ 7000',
    cat: 'Série GPZ – Professionnel',
    badge: 'Premium',
    badgeClass: 'new',
    img: 'MANTI-HERO.png',
    stars: 5,
    reviews: 32,
    shortDesc: 'Technologie ZVT™ exclusive, détecte l\'or jusqu\'à 40% plus profond que tout autre détecteur. Référence mondiale.',
    longDesc: `Le Minelab GPZ 7000 est la référence absolue en matière de détection d'or en profondeur. Sa technologie brevétée ZVT™ (Zero Voltage Transmission) lui permet de détecter l'or jusqu'à 40% plus profond que les meilleurs détecteurs à impulsions. Grâce à sa bobine Super-D de 14", il couvre une large surface tout en maintenant une sensibilité exceptionnelle aux petites et grosses pépites. Son système GPS intégré vous permet de cartographier vos zones de prospection. C'est le choix des professionnels qui cherchent des résultats extraordinaires.`,
    specs: [
      { label: 'Technologie', value: 'ZVT™ (Zero Voltage Transmission)' },
      { label: 'GPS', value: 'Intégré avec cartographie' },
      { label: 'Profondeur', value: '+40% vs détecteurs PI standard' },
      { label: 'Poids', value: '2,95 kg' },
      { label: 'Autonomie', value: '8+ heures' },
      { label: 'Bobine incluse', value: 'Super-D 14" GPZ' },
      { label: 'Waterproof', value: 'Oui (tête de détection)' },
      { label: 'Garantie', value: '2 ans constructeur' },
    ],
    features: [
      'GPS intégré pour cartographie de terrain',
      'Système de réjection des parasites avancé',
      'Affichage couleur haute résolution',
      'Compatible avec toutes les bobines GPZ',
      'Mode Gold Chance Indicator',
    ],
    related: [0, 2, 5]
  },
  {
    id: 2,
    name: 'Minelab SDC 2300',
    cat: 'Série SDC – Professionnel',
    badge: null,
    badgeClass: '',
    img: 'VANQUISH-540_ProductImage-1.png',
    stars: 5,
    reviews: 21,
    shortDesc: 'Compact, pliable et waterproof. Technologie Pulse Induction, idéal pour terrains difficiles et ruisseaux aurifères.',
    longDesc: `Le Minelab SDC 2300 est le détecteur professionnel le plus polyvalent de la gamme. Sa conception compacte et pliable le rend facile à transporter dans les zones reculées, tandis que sa résistance à l'eau (jusqu'à 3m de profondeur) en fait le compagnon idéal pour la prospection dans les rivières et ruisseaux aurifères. Sa technologie Pulse Induction multi-période lui confère une excellente sensibilité aux pépites de toute taille dans les terrains les plus minéralisés d\'Afrique de l\'Ouest.`,
    specs: [
      { label: 'Technologie', value: 'Pulse Induction Multi-Période' },
      { label: 'Waterproof', value: 'Jusqu\'à 3 mètres de profondeur' },
      { label: 'Design', value: 'Compact pliable' },
      { label: 'Poids', value: '1,95 kg' },
      { label: 'Autonomie', value: '8+ heures' },
      { label: 'Bobine incluse', value: '8" Monoloop' },
      { label: 'Utilisation eau', value: 'Oui (submersible)' },
      { label: 'Garantie', value: '2 ans constructeur' },
    ],
    features: [
      'Entièrement submersible jusqu\'à 3m',
      'Design pliable ultra-compact',
      'Détection automatique du sol',
      'Adaptateur casque audio inclus',
      'Idéal ruisseaux et terrains boueux',
    ],
    related: [0, 1, 4]
  },
  {
    id: 3,
    name: 'Minelab Equinox 800',
    cat: 'Série Equinox',
    badge: 'Populaire',
    badgeClass: 'promo',
    img: 'Minelab-EQX900-Hero-sized.png',
    stars: 5,
    reviews: 57,
    shortDesc: 'Multi-fréquences simultanées MULTI-IQ®. Polyvalent, waterproof, parfait pour l\'or et les minéraux variés.',
    longDesc: `Le Minelab Equinox 800 est le détecteur polyvalent par excellence. Sa technologie MULTI-IQ® lui permet d'opérer sur plusieurs fréquences simultanément, offrant une performance optimale sur tous les types de terrain et pour tous types de cibles. Que vous cherchiez de l'or alluvionnaire, des minerais précieux, ou des artefacts métalliques, l'Equinox 800 s'adapte. Son design imperméable et sa légèreté exceptionnelle en font un compagnon idéal pour les longues sessions de prospection.`,
    specs: [
      { label: 'Technologie', value: 'MULTI-IQ® multi-fréquences' },
      { label: 'Fréquences', value: '5, 10, 15, 20, 40 kHz + Multi' },
      { label: 'Waterproof', value: 'Jusqu\'à 3 mètres' },
      { label: 'Poids', value: '1,5 kg' },
      { label: 'Autonomie', value: '12+ heures' },
      { label: 'Bobine incluse', value: 'Double-D 11"' },
      { label: 'Bluetooth', value: 'Oui (casque sans fil)' },
      { label: 'Garantie', value: '2 ans constructeur' },
    ],
    features: [
      '5 fréquences + mode multi-fréquences',
      'Bluetooth pour casque sans fil Minelab',
      'Interface simple à 4 modes de détection',
      'Léger et ergonomique',
      'Parfait tous terrains et tous minerais',
    ],
    related: [0, 4, 5]
  },
  {
    id: 4,
    name: 'Minelab Gold Monster 1000',
    cat: 'Gold Monster',
    badge: null,
    badgeClass: '',
    img: 'GM-1000_ProductImage.png',
    stars: 4,
    reviews: 83,
    shortDesc: 'Automatique, simple et redoutablement efficace. Idéal pour débutants et prospecteurs intermédiaires.',
    longDesc: `Le Minelab Gold Monster 1000 est le détecteur parfait pour démarrer la prospection aurifère. Sa technologie automatique à 45 kHz offre une sensibilité remarquable à l'or natif sans aucun réglage complexe. Allumez-le et commencez à chercher — c'est aussi simple que ça. Malgré sa facilité d'utilisation, le Gold Monster 1000 est un détecteur sérieux capable de trouver des pépites très fines inaccessibles aux détecteurs conventionnels. Idéal pour les terrains aurifères d\'Afrique de l\'Ouest.`,
    specs: [
      { label: 'Technologie', value: 'VLF haute fréquence 45 kHz' },
      { label: 'Mode', value: 'Entièrement automatique' },
      { label: 'Profondeur', value: 'Excellente pour pépites fines' },
      { label: 'Poids', value: '1,0 kg' },
      { label: 'Autonomie', value: '12+ heures (piles AA)' },
      { label: 'Bobine incluse', value: '10" DD + 5" DD' },
      { label: 'Waterproof', value: 'Bobine imperméable' },
      { label: 'Garantie', value: '2 ans constructeur' },
    ],
    features: [
      'Fonctionnement 100% automatique',
      '2 bobines fournies (10" et 5")',
      'Fonctionne avec piles AA standard',
      'Indicateur d\'intensité du signal',
      'Idéal pour débutants — prise en main immédiate',
    ],
    related: [3, 0, 5]
  },
  {
    id: 5,
    name: 'Bobines & Accessoires Minelab',
    cat: 'Accessoires Officiels',
    badge: null,
    badgeClass: '',
    img: 'GPZ19_LandingPage_Transparent.png',
    stars: 5,
    reviews: 29,
    shortDesc: 'Bobines de recherche, protections, chargeurs et accessoires 100% originaux Minelab.',
    longDesc: `LoubaShop propose une gamme complète d'accessoires officiels Minelab pour optimiser et prolonger la vie de votre équipement. Des bobines de différentes tailles pour s'adapter à chaque terrain, aux protections et étuis, en passant par les chargeurs et câbles de remplacement — tout ce dont vous avez besoin pour être au maximum de vos performances sur le terrain. Tous nos accessoires sont 100% originaux Minelab avec garantie constructeur.`,
    specs: [
      { label: 'Compatibilité', value: 'GPX, GPZ, SDC, Equinox, Gold Monster' },
      { label: 'Bobines', value: 'Mono, Double-D, Super-D' },
      { label: 'Tailles', value: '5", 8", 10", 11", 14", 17"' },
      { label: 'Protections', value: 'Étuis rigides, coques, sangles' },
      { label: 'Chargeurs', value: 'USB-C, secteur, solaire' },
      { label: 'Authenticité', value: '100% originaux Minelab' },
      { label: 'Garantie', value: 'Garantie constructeur incluse' },
    ],
    features: [
      'Bobines officielles toutes tailles',
      'Protections et étuis de transport',
      'Chargeurs et batteries de remplacement',
      'Câbles et connecteurs audio',
      'Casques audio sans fil Minelab',
    ],
    related: [0, 1, 3]
  }
];
